apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
    tier: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        tier: mongodb
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}:{{ .Values.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
      restartPolicy: {{ .Values.restartPolicy }}