apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: LoadBalancer
  selector:
    app: devops-project
    tier: devops-project
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: 8080