name: Docker build,tag and push to DockerHub
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
    
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build image for MongoDB
          run: |
            docker build -t pavelkitanov/mongodb ./mongoDb 
            
        - name: Build image for application
          run: |
            docker build -t pavelkitanov/application .
            
        - name: Docker tag for MongoDB
          run: |
            docker tag pavelkitanov/mongodb pavelkitanov/mongodb
            
        - name: Docker tag for application
          run: |
            docker tag pavelkitanov/application pavelkitanov/application
        
        - name: Docker push image for MongoDB
          run: |
            docker push pavelkitanov/mongodb
        
        - name: Docker push image for application
          run: |
            docker push pavelkitanov/application
        
 
